---
- name: Install prerequisites
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Install Docker on Amazon Linux 2
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
  command: amazon-linux-extras install docker -y

- name: Install Docker on Amazon Linux 2023
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"
  yum:
    name: docker
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

